spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://192.168.99.100:9999
    auth-service:
      path: /user/**
      url: http://192.168.99.100:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://192.168.99.100:8181/uaa/user
    client:
      accessTokenUri: http://192.168.99.100:8181/uaa/oauth/token
      userAuthorizationUri: http://192.168.99.100:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://edge-service:9999
    auth-service:
      path: /user/**
      url: http://user-service:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://user-service:8181/uaa/user
    client:
      accessTokenUri: http://user-service:8181/uaa/oauth/token
      userAuthorizationUri: http://user-service:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/